feat(ordered-hash): add ordered-hash factory
ovh-ux/ng-ovh-cloud-universe-components pull request #8
Opened 2019-02-20 16:08 UTC by cbourgois

## feat(ordered-hash): add ordered-hash factory

### Description of the Change

ref: OM-312

07c13b5 — feat(ordered-hash): add ordered-hash factory

ref: 

/cc @jleveugle @frenautvh @antleblanc

2019-02-21 09:34 UTC, FredericEspiau submitted a review, later dismissed

2019-02-21 13:39 UTC, antleblanc requested changes

2019-02-21 13:39 UTC, antleblanc commented on src/orderedHash/factory.js
> +// import angular from 'angular';
Could be deleted!

2019-02-22 15:39 UTC, cbourgois commented
Rebased on `develop` + fixes

2019-02-22 15:50 UTC, FredericEspiau approved these changes

2019-02-22 15:50 UTC, antleblanc approved these changes

2019-02-22 15:51 UTC, merged